INSERT INTO Individual VALUES ('1','101','Africa');
INSERT INTO Individual VALUES ('2','102','South America');
INSERT INTO Individual VALUES ('3','103','North America');
INSERT INTO Individual VALUES ('4','104','Austrilia');
INSERT INTO Individual VALUES ('5','105','Asia');
INSERT INTO Individual VALUES ('6','106','South America');
INSERT INTO Individual VALUES ('7','107','Europe');
INSERT INTO Individual VALUES ('8','108','North America');
INSERT INTO Individual VALUES ('9','109','South America');
INSERT INTO Individual VALUES ('10','110','South America');
INSERT INTO Individual VALUES ('11','111','Africa');
INSERT INTO Individual VALUES ('12','112','South America');
INSERT INTO Individual VALUES ('13','113','Austrilia');
INSERT INTO Individual VALUES ('14','114','Europe');
INSERT INTO Individual VALUES ('15','115','Europe');
INSERT INTO Individual VALUES ('16','116','South America');
INSERT INTO Individual VALUES ('17','117','North America');
INSERT INTO Individual VALUES ('18','118','Europe');
INSERT INTO Individual VALUES ('19','119','Asia');
INSERT INTO Individual VALUES ('20','120','North America');
INSERT INTO Individual VALUES ('21','121','South America');
INSERT INTO Individual VALUES ('22','122','Africa');
INSERT INTO Individual VALUES ('23','123','Asia');
INSERT INTO Individual VALUES ('24','124','Africa');
INSERT INTO Individual VALUES ('25','125','Austrilia');
INSERT INTO Individual VALUES ('26','126','North America');
INSERT INTO Individual VALUES ('27','127','Europe');
INSERT INTO Individual VALUES ('28','128','Europe');
INSERT INTO Individual VALUES ('29','129','Europe');
INSERT INTO Individual VALUES ('30','130','Africa');
INSERT INTO Individual VALUES ('31','131','Europe');
INSERT INTO Individual VALUES ('32','132','Austrilia');
INSERT INTO Individual VALUES ('33','133','Europe');
INSERT INTO Individual VALUES ('34','134','Europe');
INSERT INTO Individual VALUES ('35','135','Asia');
INSERT INTO Individual VALUES ('36','136','Asia');
INSERT INTO Individual VALUES ('37','137','Europe');
INSERT INTO Individual VALUES ('38','138','Austrilia');
INSERT INTO Individual VALUES ('39','139','North America');
INSERT INTO Individual VALUES ('40','140','Europe');
INSERT INTO Individual VALUES ('41','141','Austrilia');
INSERT INTO Individual VALUES ('42','142','Africa');
INSERT INTO Individual VALUES ('43','143','Austrilia');
INSERT INTO Individual VALUES ('44','144','Austrilia');
INSERT INTO Individual VALUES ('45','145','Asia');
INSERT INTO Individual VALUES ('46','146','Europe');
INSERT INTO Individual VALUES ('47','147','Austrilia');
INSERT INTO Individual VALUES ('48','148','Africa');
INSERT INTO Individual VALUES ('49','149','Austrilia');
INSERT INTO Individual VALUES ('50','150','Europe');
INSERT INTO Individual VALUES ('51','151','Asia');
INSERT INTO Individual VALUES ('52','152','South America');
INSERT INTO Individual VALUES ('53','153','Asia');
INSERT INTO Individual VALUES ('54','154','Europe');
INSERT INTO Individual VALUES ('55','155','South America');
INSERT INTO Individual VALUES ('56','156','Europe');
INSERT INTO Individual VALUES ('57','157','Europe');
INSERT INTO Individual VALUES ('58','158','South America');
INSERT INTO Individual VALUES ('59','159','Europe');
INSERT INTO Individual VALUES ('60','160','Asia');
INSERT INTO Individual VALUES ('61','161','Austrilia');
INSERT INTO Individual VALUES ('62','162','South America');
INSERT INTO Individual VALUES ('63','163','Africa');
INSERT INTO Individual VALUES ('64','164','Austrilia');
INSERT INTO Individual VALUES ('65','165','Europe');
INSERT INTO Individual VALUES ('66','166','North America');
INSERT INTO Individual VALUES ('67','167','Africa');
INSERT INTO Individual VALUES ('68','168','South America');
INSERT INTO Individual VALUES ('69','169','Europe');
INSERT INTO Individual VALUES ('70','170','Asia');
INSERT INTO Individual VALUES ('71','171','South America');
INSERT INTO Individual VALUES ('72','172','Asia');
INSERT INTO Individual VALUES ('73','173','Austrilia');
INSERT INTO Individual VALUES ('74','174','Austrilia');
INSERT INTO Individual VALUES ('75','175','South America');
INSERT INTO Individual VALUES ('76','176','South America');
INSERT INTO Individual VALUES ('77','177','North America');
INSERT INTO Individual VALUES ('78','178','Asia');
INSERT INTO Individual VALUES ('79','179','North America');
INSERT INTO Individual VALUES ('80','180','North America');
INSERT INTO Individual VALUES ('81','181','Austrilia');
INSERT INTO Individual VALUES ('82','182','South America');
INSERT INTO Individual VALUES ('83','183','Asia');
INSERT INTO Individual VALUES ('84','184','Europe');
INSERT INTO Individual VALUES ('85','185','South America');
INSERT INTO Individual VALUES ('86','186','Austrilia');
INSERT INTO Individual VALUES ('87','187','Africa');
INSERT INTO Individual VALUES ('88','188','Europe');
INSERT INTO Individual VALUES ('89','189','Austrilia');
INSERT INTO Individual VALUES ('90','190','Europe');
INSERT INTO Individual VALUES ('91','191','South America');
INSERT INTO Individual VALUES ('92','192','Asia');
INSERT INTO Individual VALUES ('93','193','Africa');
INSERT INTO Individual VALUES ('94','194','South America');
INSERT INTO Individual VALUES ('95','195','North America');
INSERT INTO Individual VALUES ('96','196','Asia');
INSERT INTO Individual VALUES ('97','197','Austrilia');
INSERT INTO Individual VALUES ('98','198','Africa');
INSERT INTO Individual VALUES ('99','199','Austrilia');
INSERT INTO Individual VALUES ('100','200','Austrilia');
