INSERT INTO productsubcategory VALUES ('1','1','Audio');
INSERT INTO productsubcategory VALUES ('2','1','Cameras');
INSERT INTO productsubcategory VALUES ('3','1','Communications');
INSERT INTO productsubcategory VALUES ('4','1','General electronic');
INSERT INTO productsubcategory VALUES ('5','2','Video');
INSERT INTO productsubcategory VALUES ('6','2','Office Equipment');
INSERT INTO productsubcategory VALUES ('7','2','Office Furniture');
INSERT INTO productsubcategory VALUES ('8','2','Office Supplies');
INSERT INTO productsubcategory VALUES ('9','2','General office');
INSERT INTO productsubcategory VALUES ('10','3','Equipment');
INSERT INTO productsubcategory VALUES ('11','3','Fishing');
INSERT INTO productsubcategory VALUES ('12','3','Hunting');
INSERT INTO productsubcategory VALUES ('13','3','Sports Memorabilia');
INSERT INTO productsubcategory VALUES ('14','3','Sportswear');
INSERT INTO productsubcategory VALUES ('15','3','Tickets');
INSERT INTO productsubcategory VALUES ('16','4','Bathroom');
INSERT INTO productsubcategory VALUES ('17','4','Electrical');
INSERT INTO productsubcategory VALUES ('18','4','Furniture');
INSERT INTO productsubcategory VALUES ('19','4','Garden');
INSERT INTO productsubcategory VALUES ('20','4','Hobbies');
INSERT INTO productsubcategory VALUES ('21','4','Home Decor');
INSERT INTO productsubcategory VALUES ('22','4','Safety');
INSERT INTO productsubcategory VALUES ('23','5','Collectible Cards');
INSERT INTO productsubcategory VALUES ('24','5','Dolls & Plush');
INSERT INTO productsubcategory VALUES ('25','5','Educational');
INSERT INTO productsubcategory VALUES ('26','5','Gambling');
INSERT INTO productsubcategory VALUES ('27','5','General toy');
INSERT INTO productsubcategory VALUES ('28','5','Outdoor');
INSERT INTO productsubcategory VALUES ('29','5','Puzzles');
INSERT INTO productsubcategory VALUES ('30','5','Video Games');
